# Generated by Django 4.1.7 on 2023-02-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AlterField(
            model_name='message',
            name='messeage',
            field=models.CharField(default='default message', max_length=200),
        ),
    ]
