# Generated by Django 4.1.7 on 2023-02-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_message_email_message_name_message_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messeage',
            new_name='message',
        ),
    ]
